// <auto-generated />
using CalendarPlanr.DomainModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CalendarPlanr.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180310061020_Edited")]
    partial class Edited
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalendarPlanr.DomainModel.CEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<int>("LoginID");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("LoginID");

                    b.ToTable("CEvent");
                });

            modelBuilder.Entity("CalendarPlanr.DomainModel.CLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Pin");

                    b.HasKey("Id");

                    b.ToTable("CLogin");
                });

            modelBuilder.Entity("CalendarPlanr.DomainModel.CEvent", b =>
                {
                    b.HasOne("CalendarPlanr.DomainModel.CLogin", "CLogin")
                        .WithMany()
                        .HasForeignKey("LoginID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
